### PR TITLE
Remove unused variable

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Review by PetervDooren — COMMENTED** [review]
Just because it is currently not used does not mean it is useless.

**Comment by MatthijsBurgh** [comment]
I don't even get what it should do. When you render minimal 1 pixel, it is set to true.

When it was really clear what it is doing, but unused, I could agree we can keep it. But that it isn't the case for here. So therefore I still think we should remove it.

**Comment by PetervDooren** [comment]
> I don't even get what it should do. When you render minimal 1 pixel, it is set to true.
> 
> When it was really clear what it is doing, but unused, I could agree we can keep it. But that it isn't the case for here. So therefore I still think we should remove it.

So it informs you if the thing you rendered is in view. Which is good information I believe

**Comment by MatthijsBurgh** [comment]
Then it should be reset for every render call. That is not done. Plus we don't use it. And it is not part of a library, but just this plugin. So really no need to keep it.

**Comment by LarsJanssenTUe** [comment]
> > I don't even get what it should do. When you render minimal 1 pixel, it is set to true.
> > When it was really clear what it is doing, but unused, I could agree we can keep it. But that it isn't the case for here. So therefore I still think we should remove it.
> 
> So it informs you if the thing you rendered is in view. Which is good information I believe

Yes and no, I agree that it does not have to be useless, but in this case, if the information is not used and not outputted there is, in my opinion, no reason to keep it. There also is not really a reason to get rid of it (except that it cleans up the code). So I think I would get rid of it. (Sorry for budding in by the way @MatthijsBurgh brought me in ;))

**Review by PetervDooren — APPROVED** [review]

**Pull request merged**
